---
title: "EDA"
author: "Derek Situ"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, here, janitor, fixest, modelsummary)

# Load data
data <- read_csv(here("data", "processed", "data.csv"))
# Load top institutions data
top_institutions <- read_csv(here("data", "raw", "top_institutions.csv"))
# Load bans data
bans <- read_csv(here("data", "raw", "bans.csv"))

# Plot --------------------------------------------------------------------
sums_by_state <- data %>%
  #filter(top_institution == 1) %>%
  group_by(state, ban_start, year, level) %>%
  summarize_at(vars(white_men:white), sum, na.rm = TRUE) %>%
  pivot_longer(cols = white_men:white,
               names_to = "group", values_to = "count")

# Plots for minority/white
for (stat in unique(bans$state)) {
  sums_by_state_plot <- sums_by_state %>%
    filter(level == "Bachelor's degree",
           state == stat,
           group %in% c("white", "minority"))
  
  print(ggplot(sums_by_state_plot,
               aes(x = year,
                   y = count,
                   colour = group)) +
          geom_line() +
          # Add a vertical line at the year of the ban
          geom_vline(aes(xintercept = ban_start), linetype = "dashed") +
          scale_x_continuous(breaks = seq(1996, 2022, 2)) +
          labs(title = stat))
}

# Plots for men/women
for (stat in unique(bans$state)) {
  sums_by_state_plot <- sums_by_state %>%
    filter(level == "Bachelor's degree",
           state == stat,
           group %in% c("men", "women"))
  
  print(ggplot(sums_by_state_plot,
               aes(x = year,
                   y = count,
                   colour = group)) +
          geom_line() +
          # Add a vertical line at the year of the ban
          geom_vline(aes(xintercept = ban_start), linetype = "dashed") +
          scale_x_continuous(breaks = seq(1996, 2022, 2)) +
          labs(title = stat))
}

sums_by_state_2 <- data %>%
  group_by(state, ban_start, year, level) %>%
  summarize(men = sum(men),
            women = sum(women),
            minority = sum(minority),
            white = sum(white),
            prop_women = women / (men + women),
            prop_minority = minority / (minority + white))

sums_by_state_2 %>%
  filter(!is.na(ban_start)) %>%
  ggplot(aes(x = year,
             y = prop_women,
             color = state)) +
  geom_smooth(se = FALSE)

sums_by_state_2 %>%
  filter(!is.na(ban_start)) %>%
  ggplot(aes(x = year,
             y = prop_minority,
             color = state)) +
  geom_smooth(se = FALSE)
```

